import numpy as np

EPS = 1e-5

DICO_COMPATIBILITY ={
    "AC Ajaccio": 'Ajaccio',
    "Lyon":"Lyon",
    "Rennes":"Rennes",
    "Paris SG":"Paris SG",
    "Nantes":"Nantes",
    "Lens":"Lens", 
    "Troyes":"Troyes",
    "Reims":"Reims",
    "Nice":"Nice", 
    "Montpellier":"Montpellier", 
    "Toulouse":"Toulouse",
    "Strasbourg":"Strasbourg", 
    "Lille":"Lille", 
    "Auxerre":"Auxerre", 
    "Brest":"Brest", 
    "Clermont":"Clermont", 
    "Lorient":"Lorient", 
    "Angers":"Angers", 
    "Monaco":"Monaco", 
    "Marseille":"Marseille",
    "Sochaux": "Sochaux",
    "Bastia": "Bastia",
    "Valenciennes": "Valenciennes",
    "Guingamp": "Guingamp",
    "Nîmes":"Nimes",
    "St Etienne": "St Etienne", 
    "Grenoble": "Grenoble",
    "Rodez": "Rodez", 
    "Metz": "Metz", 
    "Pau": "Pau FC", 
    "Laval": "Laval", 
    "Grenoble": "Grenoble",
    "Bordeaux": "Bordeaux",
    "Caen": "Caen", 
    "Paris FC": "Paris FC", 
    "Dijon": "Dijon",
    "Quevilly Rouen": "Quevilly Rouen", 
    "Niort": "Niort", 
    "Amiens": "Amiens", 
    "Le Havre": "Le Havre",
    "Annecy FC":"Annecy",
}